In [2]:
#All necessary Imports
from pandas import read_csv
from datetime import datetime
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import cross_validation
import matplotlib.pyplot as plt
import seaborn as sns

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [3]:
%matplotlib notebook

dataset = read_csv('ks-projects-201801.csv')
print(dataset.keys()) # important keys for the data
column = ['ID', 'name', 'category', 'main_category', 'currency', 'deadline',
       'goal', 'launched', 'pledged', 'state', 'backers', 'country',
       'usd pledged', 'usd_pledged_real', 'usd_goal_real']
df1 = (pd.DataFrame(dataset, columns= column))
encoder = preprocessing.LabelEncoder()
encoder.fit(df1.state)
target_encoded = encoder.transform(df1.state)

#Encoding target values to numericals:
for i,item in enumerate(encoder.classes_):
    print(item, '=', i)
print('\n')
#adding target as numericals and dropping state column.
df1['target']= target_encoded
df1.drop(['state'],1, inplace=True)
 1 

#Encoding Main_category to numericals:
encoder1 = preprocessing.LabelEncoder()
encoder1.fit(df1.main_category)
main_category_encoded = encoder1.transform(df1.main_category)
for i,item in enumerate(encoder1.classes_):
    print(item, '=', i)
print('\n')
df1['main_category'] = main_category_encoded

#calculating the difference of dates from the date of launch to the deadline date.
a = dataset['launched']
b = dataset['deadline']
new=pd.DataFrame(columns=['time'])
new
new['time'] = (pd.to_datetime(b) - pd.to_datetime(a)).map(lambda x:x.days)
new['time']
#adding the date difference in Feature list
df1['time'] = new['time']

Index(['ID', 'name', 'category', 'main_category', 'currency', 'deadline',
       'goal', 'launched', 'pledged', 'state', 'backers', 'country',
       'usd pledged', 'usd_pledged_real', 'usd_goal_real'],
      dtype='object')
canceled = 0
failed = 1
live = 2
successful = 3
suspended = 4
undefined = 5


Art = 0
Comics = 1
Crafts = 2
Dance = 3
Design = 4
Fashion = 5
Film & Video = 6
Food = 7
Games = 8
Journalism = 9
Music = 10
Photography = 11
Publishing = 12
Technology = 13
Theater = 14

In [6]:
#selected features and target:
df2 = df1
#df2 after various non related features dropped:
df2.drop(['ID'],axis=1,inplace = True)
#Do this for non numeric features and transformed features.


#Scaling Features using MinMaxScalar but having problems..

#scaler=preprocessing.MinMaxScaler().fit(df2)
#df2_transformed = scaler.transform(df2)

ValueError: labels ['ID'] not contained in axis

In [5]:
#correlation matrix with all features against target
corr = df2_transfomed.corr()
# Generate a mask for the upper triangle
mask = np.zeros_like(corr, dtype=np.bool)
mask[np.triu_indices_from(mask)] = True
# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(11, 9))
# Generate a custom diverging colormap
cmap = sns.diverging_palette(220, 10, as_cmap=True)
# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr,mask=mask, cmap=cmap, vmax=1, center=0, square=True, linewidths=.1, cbar_kws={"shrink": .7})

NameError: name 'df2_transfomed' is not defined

# Features mostly correlated to target(state) = usd_pledged_real, backers, usd_goal_real, time, category.

In [62]:
X = df2[['main_category','backers','usd_pledged_real','usd_goal_real','time']].values
Y = df2.target
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,random_state=0)
print('shape of X_train is:', X_train.shape)
print('shape of X_test is:', X_test.shape)

/Users/echhitjoshi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

       main_category  usd_pledged_real  usd_goal_real       state  times
0         Publishing              0.00        1533.95      failed     58
1       Film & Video           2421.00       30000.00      failed     59
2       Film & Video            220.00       45000.00      failed     44
3              Music              1.00        5000.00      failed     29
4       Film & Video           1283.00       19500.00    canceled     55
5               Food          52375.00       50000.00  successful     34
6               Food           1205.00        1000.00  successful     19
7               Food            453.00       25000.00      failed     44
8             Design           8233.00      125000.00    canceled     34
9       Film & Video           6240.57       65000.00    canceled     29
10        Publishing              0.00        2406.39      failed     29
11             Music          12700.00       12500.00  successful     29
12            Crafts              0.00        5000.00      failed     29
13             Games              0.00      200000.00      failed     44
14             Games         121857.33        6469.73  successful     27
15            Design            664.00        2500.00      failed     29
16            Comics            395.00        1500.00      failed     29
17        Publishing            789.00        3000.00      failed     29
18             Music            250.00         250.00  successful     14
19              Food           1781.00        5000.00      failed     29
20           Fashion          34268.00       20000.00  successful     34
21           Fashion              0.81        2026.10      failed     29
22           Theater            650.00        3500.00      failed     29
23              Food              6.29          65.55      failed     29
24            Comics            701.66         175.00  successful     19
25             Music          15827.00       10000.00  successful     29
26            Crafts              0.00       17489.65      failed     29
27      Film & Video          42174.03       15313.04  successful     29
28            Comics            160.60         142.91  successful     29
29      Film & Video          57577.31       50000.00  successful     29
...              ...               ...            ...         ...    ...
378631         Games          13861.50       10000.00  successful     29
378632  Film & Video              0.00       12000.00      failed     29
378633       Fashion          11643.00       25000.00      failed     29
378634   Photography           3531.00        4000.00      failed     60
378635    Publishing             70.00         800.00      failed     29
378636         Music           4686.96        4311.83  successful     29
378637  Film & Video          10245.00       10000.00  successful     44
378638    Publishing             18.00        5000.00      failed     30
378639          Food           5579.00        5000.00  successful     29
378640    Publishing            100.00        1000.00    canceled     33
378641        Design              0.00       82207.27      failed     59
378642         Games           1452.47        1165.70  successful     26
378643    Technology              0.00        6500.00    canceled     20
378644        Design           6169.00        3500.00  successful     21
378645        Comics           4374.99       25566.05      failed     29
378646    Publishing           1732.02         950.00  successful     42
378647    Publishing            980.00        4999.00      failed     29
378648         Games            121.00         500.00    canceled     29
378649  Film & Video            135.00         500.00      failed     59
378650    Technology              0.00        6000.00      failed     37
378651         Music           4983.69        4529.81  successful     29
378652  Film & Video           2875.83        2675.19  successful     29
378653  Film & Video             25.00        1700.00      failed     29
378654          Food            154.00        6500.00      failed     29
378655    Publishing              0.00        4949.60    canceled     44
378656  Film & Video             25.00       50000.00    canceled     29
378657  Film & Video            155.00        1500.00      failed     26
378658  Film & Video             20.00       15000.00      failed     45
378659    Technology            200.00       15000.00      failed     30
378660           Art            524.00        2000.00      failed     27

[378661 rows x 5 columns]

shape of X_train is: (283995, 4)
shape of X_test is: (94666, 4)