In [2]:
from pandas import read_csv
from datetime import datetime
import numpy as np
import pandas as pd 
data = read_csv('ks-projects-201801.csv')
print(data.keys()) # important keys for the data

Index(['ID', 'name', 'category', 'main_category', 'currency', 'deadline',
       'goal', 'launched', 'pledged', 'state', 'backers', 'country',
       'usd pledged', 'usd_pledged_real', 'usd_goal_real'],
      dtype='object')

In [34]:
new=pd.DataFrame(columns=['time'])
new

Empty DataFrame
Columns: [time]
Index: []

In [45]:
new=pd.DataFrame(columns=['time'])
a = data['launched']
b = data['deadline']
new['time'] = (pd.to_datetime(b) - pd.to_datetime(a)).map(lambda x:x.days)
new['time']

0         58
1         59
2         44
3         29
4         55
5         34
6         19
7         44
8         34
9         29
10        29
11        29
12        29
13        44
14        27
15        29
16        29
17        29
18        14
19        29
20        34
21        29
22        29
23        29
24        19
25        29
26        29
27        29
28        29
29        29
          ..
378631    29
378632    29
378633    29
378634    60
378635    29
378636    29
378637    44
378638    30
378639    29
378640    33
378641    59
378642    26
378643    20
378644    21
378645    29
378646    42
378647    29
378648    29
378649    59
378650    37
378651    29
378652    29
378653    29
378654    29
378655    44
378656    29
378657    26
378658    45
378659    30
378660    27
Name: time, Length: 378661, dtype: int64

In [44]:
import datetime
x=a.map(lambda x:x.days)
x

AttributeError: 'str' object has no attribute 'days'

In [29]:
#calculating the difference of dates from the date of launch to the deadline date.
total = len(data)
dateDifference = []
    
for x in range(0,total):
    a = data['launched'][x][:10]
    b = data['deadline'][x]
    date_format = "%Y-%m-%d"
    a = datetime.strptime(a, date_format)
    b = datetime.strptime(b, date_format)
    s=str(b-a)
    dif=int(s.split()[0])
    new.loc[x]=dif
print(new)

KeyboardInterrupt:

In [30]:
new

      time
0       59
1       60
2       45
3       30
4       56
5       35
6       20
7       45
8       35
9       30
10      30
11      30
12      30
13      45
14      28
15      30
16      30
17      30
18      15
19      30
20      35
21      30
22      30
23      30
24      20
25      30
26      30
27      30
28      30
29      30
...    ...
94383   44
94384   24
94385   16
94386   21
94387   30
94388   30
94389   30
94390   35
94391   30
94392   30
94393   31
94394   22
94395   30
94396   30
94397   60
94398   28
94399   45
94400   30
94401   30
94402   42
94403   26
94404    7
94405   30
94406   30
94407   30
94408   52
94409   30
94410   30
94411   30
94412   30

[94413 rows x 1 columns]

In [ ]:
#selecting features
X = data[['category','usd_pledged_real','usd_goal_real']]
Y = data['state']

In [ ]:
X['times']=new['time']
X

In [ ]:
for x in range(0,10):
    a = data['launched'][x][:10]
    b = data['deadline'][x]
    date_format = "%Y-%m-%d"
    a = datetime.strptime(a, date_format)
    b = datetime.strptime(b, date_format)
    delta = b - a
    dateDifference.append(delta)

In [31]:
  date_format = "%Y-%m-%d"
    a = datetime.strptime(a, date_format)
    b = datetime.strptime(b, date_format)

IndentationError: unexpected indent (<ipython-input-31-c4dab6c1041b>, line 2)

In [32]:
??pd